apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: examen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:latest
          ports:
            - containerPort: 8080
          env:
            - name: WORDPRESS_DATABASE_HOST
              value: mariadb-service
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
            - name: WORDPRESS_DATABASE_USER
              value: wpuser
            - name: WORDPRESS_DATABASE_PASSWORD
              value: wppass123
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: examen
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
